# Hyprpaper 0.8+: an empty monitor is the fallback for all outputs.
wallpaper {
    monitor =
    path = {{ wallpaper_path | default('/home/magnus/testdata/images/VNLNEWOR003_front-scaled.jpg') }}
    fit_mode = cover
}
