general {
    lock_cmd = pidof hyprlock || hyprlock     # avoids starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session  # lock before system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after waking up
}

listener {
    timeout = 300                                 # 5 minutes in seconds
    on-timeout = loginctl lock-session            # command to run when timeout is reached
}
